param(
  [string]$ConfigFile = "config.yaml",
  [string]$ModelPath,
  [string]$ServerBinary,
  [string]$ApiHost = "0.0.0.0",
  [int]$ApiPort = 8010,
  [int]$UiPort = 3000,
  [int]$BaseModelPort = 8080,
  [int]$MaxPortSearch = 20,
  [switch]$SkipModel,
  [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path $scriptDir -Parent
Set-Location $repoRoot

$defaultModelPath = "C:\Users\loudo\Desktop\bonsai-chatbot\bonsai-chatbot\models\bonsai-gguf.gguf"
$defaultServerBinary = "C:\Users\loudo\llama.cpp\build\bin\Release\llama-server.exe"
$logsDir = Join-Path $repoRoot "logs"
$modelStdout = Join-Path $logsDir "llama-server-stdout.log"
$modelStderr = Join-Path $logsDir "llama-server-stderr.log"
$apiStdout = Join-Path $logsDir "api-stdout.log"
$apiStderr = Join-Path $logsDir "api-stderr.log"
$uiStdout = Join-Path $logsDir "ui-stdout.log"
$uiStderr = Join-Path $logsDir "ui-stderr.log"

if (-not $ModelPath) { $ModelPath = $defaultModelPath }
if (-not $ServerBinary) { $ServerBinary = $defaultServerBinary }

Write-Host "[INFO] Repo root: $repoRoot" -ForegroundColor Cyan
Write-Host "[INFO] Model path: $ModelPath"
Write-Host "[INFO] llama-server path: $ServerBinary"
Write-Host "[INFO] Base model port: $BaseModelPort (searching up to $MaxPortSearch ports)"

New-Item -ItemType Directory -Force -Path $logsDir | Out-Null

function Fail-AndPause {
  param([string]$Message)
  Write-Host "[ERROR] $Message" -ForegroundColor Red
  Write-Host "[INFO] Logs live in $logsDir" -ForegroundColor Yellow
  Read-Host "Press Enter to exit" | Out-Null
  exit 1
}

function Get-AvailablePort {
  param(
    [int]$StartingPort,
    [int]$MaxAttempts = 20,
    [string]$Name = "port"
  )
  $port = $StartingPort
  for ($i = 0; $i -lt $MaxAttempts; $i++) {
    $listener = $null
    try {
      $listener = [System.Net.Sockets.TcpListener]::Create($port)
      $listener.Start()
      return $port
    } catch {
      $port++
    } finally {
      if ($listener) { $listener.Stop() }
    }
  }
  throw "No open $Name found between $StartingPort and $($StartingPort + $MaxAttempts - 1)."
}

function Ensure-VenvPython {
  param(
    [string]$RepoRoot,
    [string]$BootstrapPython
  )

  $venvPython = Join-Path $RepoRoot ".venv\\Scripts\\python.exe"
  if (Test-Path $venvPython) {
    return $venvPython
  }

  if (-not $BootstrapPython) {
    throw "Python not found to create virtual environment."
  }

  Write-Host "[INFO] Creating virtual environment (.venv)..." -ForegroundColor Yellow
  & $BootstrapPython -m venv (Join-Path $RepoRoot ".venv") | Out-Null
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to create virtual environment using $BootstrapPython."
  }

  $venvPython = Join-Path $RepoRoot ".venv\\Scripts\\python.exe"
  if (-not (Test-Path $venvPython)) {
    throw "Virtual environment creation did not produce $venvPython"
  }

  Write-Host "[INFO] Installing Python dependencies into .venv..." -ForegroundColor Yellow
  & $venvPython -m pip install --upgrade pip | Out-Null
  & $venvPython -m pip install -r (Join-Path $RepoRoot "app\\requirements.txt")
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to install app requirements into .venv."
  }

  return $venvPython
}

function Write-UiConfig {
  param(
    [string]$RepoRoot,
    [string]$ApiBase
  )

  $uiConfigPath = Join-Path $RepoRoot "ui\\config.js"
  $content = @"
// Auto-generated by scripts/quick_launch.ps1
window.BONSAI_API_BASE = "$ApiBase";
"@
  Set-Content -Path $uiConfigPath -Value $content -Encoding UTF8
}

function Start-LoggedProcess {
  param(
    [string]$Name,
    [string]$FilePath,
    [string[]]$Args = @(),
    [string]$StdoutPath,
    [string]$StderrPath,
    [string]$WorkingDir,
    [int]$ValidateSeconds = 3
  )

  if (-not (Test-Path $FilePath)) {
    throw "$Name failed to start because file was not found: $FilePath"
  }

  $cleanArgs = @()
  if ($Args) {
    $cleanArgs = $Args | Where-Object { $_ -ne $null -and "$_" -ne "" }
    if ($cleanArgs.Count -ne $Args.Count) {
      throw "$Name received an empty or null argument. Please check the inputs."
    }
  }

  $startParams = @{
    FilePath               = $FilePath
    WorkingDirectory       = $WorkingDir
    RedirectStandardOutput = $StdoutPath
    RedirectStandardError  = $StderrPath
    WindowStyle            = "Hidden"
    PassThru               = $true
  }
  if ($cleanArgs.Count -gt 0) {
    $startParams.ArgumentList = $cleanArgs
  }

  $proc = Start-Process @startParams
  Start-Sleep -Milliseconds 400
  Wait-Process -Id $proc.Id -Timeout 1 -ErrorAction SilentlyContinue | Out-Null

  $startTime = Get-Date
  while ($true) {
    if ($proc.HasExited) {
      $code = $proc.ExitCode
      $errTail = ""
      if (Test-Path $StderrPath) {
        $errTail = (Get-Content -Path $StderrPath -Tail 40 -ErrorAction SilentlyContinue) -join "`n"
      }
      $outTail = ""
      if (Test-Path $StdoutPath) {
        $outTail = (Get-Content -Path $StdoutPath -Tail 20 -ErrorAction SilentlyContinue) -join "`n"
      }
      $msg = "$Name exited with code $code. Command: `"$FilePath`" $($Args -join ' ')."
      if ($errTail) { $msg += "`nLast stderr lines:`n$errTail" }
      if (-not $errTail -and $outTail) { $msg += "`nLast stdout lines:`n$outTail" }
      if ($Name -eq "api" -and $errTail -match "bind.*10048|port.*in use") {
        $msg += "`nPort conflict detected. Rerun with -ApiPort <port> or stop the conflicting process."
      }
      if ($Name -eq "ui" -and $errTail -match "bind|address already in use") {
        $msg += "`nPort conflict detected. Rerun with -UiPort <port> or stop the conflicting process."
      }
      throw $msg
    }
    $elapsed = (Get-Date) - $startTime
    if ($elapsed.TotalSeconds -ge $ValidateSeconds) { break }
    Start-Sleep -Milliseconds 300
  }

  Write-Host "[STARTED] $Name (stdout: $StdoutPath, stderr: $StderrPath)"
  return $proc
}

try {
  $env:PYTHONNOUSERSITE = "1"

  $pythonCmd = $null
  $bootstrapPython = $null
  $venvPython = Join-Path $repoRoot ".venv\\Scripts\\python.exe"
  if (Test-Path $venvPython) {
    $pythonCmd = $venvPython
    Write-Host "[INFO] Using existing venv Python at $pythonCmd" -ForegroundColor Cyan
  } else {
    if ($cmd = Get-Command "python" -ErrorAction SilentlyContinue) {
      $bootstrapPython = $cmd.Path
      Write-Host "[INFO] Using Python from PATH to create .venv: $bootstrapPython" -ForegroundColor Cyan
    } elseif (Get-Command "py" -ErrorAction SilentlyContinue) {
      $bootstrapPython = (& py -3 -c "import sys; print(sys.executable)") -replace "`r","" -replace "`n",""
      Write-Host "[INFO] Using Windows Python launcher to create .venv: $bootstrapPython" -ForegroundColor Cyan
    } else {
      throw "Python not found. Install Python 3.11+, or create a .venv, or ensure 'py'/'python' is on PATH."
    }
    $pythonCmd = Ensure-VenvPython -RepoRoot $repoRoot -BootstrapPython $bootstrapPython
    Write-Host "[INFO] Activated venv Python at $pythonCmd" -ForegroundColor Cyan
  }

  if (-not (Test-Path $ConfigFile)) {
    throw "$ConfigFile not found. Copy config.example.yaml to $ConfigFile and update paths."
  }

  $modelPort = $null
  $modelApiBase = "http://127.0.0.1:$BaseModelPort/v1"
  $processes = @()

  if (-not $SkipModel) {
    if (-not (Test-Path $ServerBinary)) {
      throw "llama-server.exe not found at $ServerBinary. Update scripts\start_model.bat and this script to point to your llama.cpp build."
    }
    $serverName = Split-Path $ServerBinary -Leaf
    if ($serverName -ieq "llama-cli.exe") {
      throw "ServerBinary points to llama-cli.exe, which does not support --host/--port. Use llama-server.exe."
    }
    if (-not (Test-Path $ModelPath)) {
      throw "Model file not found at $ModelPath. Update ModelPath to your GGUF file."
    }

    $modelPort = Get-AvailablePort -StartingPort $BaseModelPort -MaxAttempts $MaxPortSearch -Name "model port"
    if ($modelPort -ne $BaseModelPort) {
      Write-Host "[INFO] Model base port $BaseModelPort in use; switching to $modelPort." -ForegroundColor Yellow
    }

    $modelArgs = @(
      "--model", $ModelPath,
      "--alias", "local-llm",
      "--host", "127.0.0.1",
      "--port", "$modelPort",
      "--ctx-size", "4096",
      "--n-gpu-layers", "-1",
      "--embedding"
    )
    $processes += Start-LoggedProcess -Name "llama-server" -FilePath $ServerBinary -Args $modelArgs -StdoutPath $modelStdout -StderrPath $modelStderr -WorkingDir $repoRoot
    $modelApiBase = "http://127.0.0.1:$modelPort/v1"
  } else {
    Write-Host "[INFO] SkipModel set; not launching llama-server."
  }

  $env:BONSAI_MODEL_API_BASE = $modelApiBase
  Write-Host "[INFO] Routing API calls to $modelApiBase (BONSAI_MODEL_API_BASE)" -ForegroundColor Cyan

  $apiPort = Get-AvailablePort -StartingPort $ApiPort -MaxAttempts $MaxPortSearch -Name "API port"
  if ($apiPort -ne $ApiPort) {
    Write-Host "[INFO] API base port $ApiPort in use; switching to $apiPort." -ForegroundColor Yellow
  }
  $apiArgs = @("-m", "uvicorn", "app.main:app", "--host", $ApiHost, "--port", $apiPort)
  $processes += Start-LoggedProcess -Name "api" -FilePath $pythonCmd -Args $apiArgs -StdoutPath $apiStdout -StderrPath $apiStderr -WorkingDir $repoRoot

  $uiPort = Get-AvailablePort -StartingPort $UiPort -MaxAttempts $MaxPortSearch -Name "UI port"
  if ($uiPort -ne $UiPort) {
    Write-Host "[INFO] UI base port $UiPort in use; switching to $uiPort." -ForegroundColor Yellow
  }
  $uiApiBase = "http://localhost:$apiPort"
  Write-UiConfig -RepoRoot $repoRoot -ApiBase $uiApiBase
  Write-Host "[INFO] Wrote ui\\config.js pointing to $uiApiBase" -ForegroundColor Cyan
  $uiArgs = @("-m", "http.server", "$uiPort", "-d", "ui")
  $processes += Start-LoggedProcess -Name "ui" -FilePath $pythonCmd -Args $uiArgs -StdoutPath $uiStdout -StderrPath $uiStderr -WorkingDir $repoRoot

  if (-not $NoBrowser) {
    Write-Host "[INFO] Opening browser to http://localhost:$uiPort"
    Start-Process "http://localhost:$uiPort" | Out-Null
  }

  Write-Host ""
  if (-not $SkipModel -and $modelPort) {
    Write-Host "[INFO] Model server: http://127.0.0.1:$modelPort" -ForegroundColor Cyan
  }
  Write-Host ("[INFO] API:   http://{0}:{1}" -f $ApiHost, $apiPort) -ForegroundColor Cyan
  Write-Host "[INFO] UI:    http://localhost:$uiPort" -ForegroundColor Cyan
  Write-Host "[INFO] Logs:  $logsDir" -ForegroundColor Cyan
  Write-Host "[INFO] Press Enter to stop all processes." -ForegroundColor Yellow
  Read-Host | Out-Null

  foreach ($proc in $processes) {
    if ($proc -and -not $proc.HasExited) {
      try { $proc.CloseMainWindow() | Out-Null } catch {}
      Start-Sleep -Milliseconds 300
      if (-not $proc.HasExited) {
        Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
      }
    }
  }

  Write-Host "[INFO] All processes stopped." -ForegroundColor Green
} catch {
  Fail-AndPause -Message $_.Exception.Message
}
